### ISSUE TITLE
Crash with Essential + No Chat Reports

### ISSUE THREAD

**Issue by FayneAldan** [AsoDesu/IslandUtils#1] opened 2022-08-25 03:50 UTC
Somehow using IslandUtils + Essential + No Chat Reports causes a crash when joining MCC Island. And yes, all three mods (and Fabric API) are needed to reproduce.

Crash report:
https://mclo.gs/vb8Dw2F

**Comment by AsoDesu** [comment] 2022-08-26 10:52
I will look into this, thank you <3

**Comment by JOSH-Configs** [comment] 2022-08-29 13:03
Not a bug - MCCI will not allow you to join with No Chat Reports

**Comment by FayneAldan** [comment] 2022-08-29 14:56
Yes it will. I'm able to join MCCi with No Chat Reports, but it crashes if I add Essential and IslandUtils on top of that.

**Comment by JOSH-Configs** [comment] 2022-08-30 08:10
Well ur not allowed to use No Chat Reports so-

**Comment by FayneAldan** [comment] 2022-08-30 11:32
Iirc, MCC Island enforces chat signing. Enforced chat signing will kick anyone from the server who doesn't sign their messages.

No Chat Reports has proper support for this and disables itself when connecting to MCCi. 

While the issue could be ignored since NCR doesn't even work on MCCi, the biggest problem is that NCR is included in the Fabulously Optimized modpack, which a lot of players use as a base for optimized Minecraft on newer versions on Minecraft.

**Comment by AsoDesu** [comment] 2022-08-30 12:21
Sorry, I'm away atm and I haven't been able to look into this issue further, and I am not too familiar with what No Chat Reports does.
However I have identified this as an issue with IslandUtils and mods that may mess with the Clients server joining/leaving, as IslandUtils depends on data that may be often modified by other mods.
I will leave this issue open until this issue can be solved.

**Comment by DoctorKrolic** [comment] 2022-09-09 15:41
For me the issue is reproduced with only NoChatReport installed. Please fix this one, NoChatReport is kinda requirement nowadays

**Comment by FayneAldan** [comment] 2022-09-09 18:41
> For me the issue is reproduced with only NoChatReport installed. Please fix this one, NoChatReport is kinda requirement nowadays

I just tried it again and I still can't get the crash to occur with just Island Utils and NoChatReport. What mods do you have?

**Comment by AsoDesu** [comment] 2022-09-12 21:43
Should be fixed in 1.1.0, please comment back here if there are any more issues!

**Closed by AsoDesu** 2022-09-12 21:43 UTC
Labels: bug
