### ISSUE TITLE
Music not working

### ISSUE THREAD

**Issue by Kapry30GB** [AsoDesu/IslandUtils#83] opened 2023-08-16 22:06 UTC
Hi, can someone tell me why it stays at 0%??

I think it's related to the music bc it isn't working, pls help me.

![Screenshot 2023-08-17 000335](https://github.com/AsoDesu/IslandUtils/assets/73724765/08c8bdec-60ce-4d9c-8d7c-b2527750702a)

**Comment by AsoDesu** [comment] 2023-08-16 22:07
Please can you send me a log file?

**Comment by Kapry30GB** [comment] 2023-08-16 22:09
Sure, here ya go :)

[latest.log](https://github.com/AsoDesu/IslandUtils/files/12363926/latest.log)

**Comment by AsoDesu** [comment] 2023-08-17 17:07
Hmm that's weird

**Comment by Karkkikuppi** [comment] 2023-08-17 18:37
> ![Screenshot 2023-08-17 140006](https://user-images.githubusercontent.com/73724765/261301609-8395e640-fe71-440b-9665-4bba163419f8.png)

@Kapry30GB could you attach the browser error details as well? This might give some insight on why it's failing! Here's an example:

![kuva](https://github.com/AsoDesu/IslandUtils/assets/64687000/56e67c93-8ce9-4433-a307-d059269e04e8)

**Comment by AsoDesu** [comment] 2023-09-15 19:54
Okay hi, so i think i figured out what causes this
It's caused by some weird restrictions my CDN has on certain internet connections, as such next update will use a different solution, so this should be fixed when that releases

**Comment by AsoDesu** [comment] 2023-09-19 18:32
Should be fixed in 1.6.0

**Closed by AsoDesu** 2023-09-19 18:32 UTC
Labels: Bug
