### ISSUE TITLE
Add 'To the dome' music in lobbies

### ISSUE THREAD

**Issue by IndianSkeppy** [AsoDesu/IslandUtils#96] opened 2023-09-19 17:34 UTC
Considering this mod brings like a new level of joy to the games with their respective music 

I think the lobbies should not be left alone too

So my suggestion is to like add the 'To The Dome' Music while a player is in the lobby 

thanks

**Comment by AsoDesu** [comment] 2023-09-19 18:31
Duplicate of #66

**Closed as completed by AsoDesu** 2023-09-19 18:31 UTC
Labels: duplicate
