### ISSUE TITLE
Game logos when you join a game!

### ISSUE THREAD

**Issue by UltraTeal** [AsoDesu/IslandUtils#148] opened 2024-09-09 15:50 UTC
I think it would be cool to have the game logos at the start of the games instead of just titles, all the game logos are on the noxcrew press website https://drive.google.com/drive/mobile/folders/1Z8E-kxu-m4RQdopEEC93CY2UiHLSgHVl/1dPTwvRjotp2irAc_57ocT8zQFxpQD6jl/1QoJc1BJFb798OQRQE8y468umnEoTFHh3/1MpohveY8oZLHa8h1Hm8Q1YNwMARXAfEm?sort=13&direction=a and here is the link the folder that has all the logos including the shortened version of tgttos. The logos are really nice and would be very cool to see when you join a game! Idk if everyone would like this so maybe make it so you can toggle them off and on?

**Comment by AsoDesu** [comment] 2024-10-06 14:43
duplicate of #84

**Closed by AsoDesu** 2024-10-06 14:43 UTC
Labels: Enhancement, Good First Issue
